# We need sudo to install pip system-wide
sudo: required

os:
  - linux
  - osx

install:
  - sudo -H pip install coverage==3.7.1
  - sudo -H pip install coveralls

script: ./ci.sh

after_success:
  - coveralls
